### ISSUE TITLE
Can't login with either ORCID or Twitter

### ISSUE THREAD

**Issue by p4bl0-** [Impactstory/impactstory-tng#11]
Hello,

I'd like to give a try to impactstory but I can't login.
When I attempt to login with ORCID, Impactstory tells me "Sorry, we don't recognize your ORCID account!".
When I attempt with Twitter I get the same behavior.

I also tried in a fresh browser with no addons in case it was a problem caused by _μBlock_ or _HTTPS Everywhere_ but I got the same results.

For info my Twitter is `p4bl0` and my ORCID is `0000-0002-6293-3231` if it may help to grep your logs and find the cause of the problem.

Cheers,

**Comment by hpiwowar** [comment]
Sorry about that!  Thanks a lot for letting us know and the advanced detective work.  

I might have fixed it for you.  Can you try again to log in with ORCID and see if it works?  (logging in with twitter won't work because your twitter account isn't connected to your Imapctstory yet.  Once you log in with orcid you will be able to connect it on the settings page.  After that, log in with twitter should work for you too :) )

Thanks a lot for helping us to debug this!
Heather

**Comment by p4bl0-** [comment]
It now works. Thanks :).

**Comment by hpiwowar** [comment]
Great!  Thanks!!
