### ISSUE TITLE
Allow authors to correct publication entries

### ISSUE THREAD

**Issue by p4bl0-** [Impactstory/impactstory-tng#12]
Hello again,

So I'm now testing Impactstory and to my surprise it didn't find 100% open access for my papers, while they are clearly all available from multiple sources.

I saw the "add link to fulltext" button and in an attempt to do that quickly I opened multiple individual publication's page in different tabs and I accidentally made a mistake: for one paper the link I submitted does not point to the right PDF.

Namely, this paper : https://impactstory.org/u/0000-0002-6293-3231/p/gRAmPAAKwB now points to the wrong PDF because I'm stupid.

But now it seems I'm not able to fix that mistake.

Also, I think it would be nice for authors to be able to change the link even for papers Impactstory found by itself as sometimes there is a source that is better than the others (e.g., in the case of shitty OA with APC, maybe the arXiv version is kept up-to-date while the publisher's version can't change).

**Comment by jasonpriem** [comment]
Ideally we should be picking up your papers if they're open access. We use the oaDOI API (which we made pretty much just to do this) to find OA. It's getting pretty good, but still far from perfect, and is in very active development. So where we're missing open copies, you may want to fill out a bug report . You can do so here: https://goo.gl/forms/kFZUUZUeM9ze9uXr2

Agreed, ideally users could change the fulltext link: either to fix errors, or just to swap out the one we found for a better one, as you suggest. Right now that's on the roadmap but it's some distance away because it's not currently a common use case.

We can fix the particular one you're mentioning right now, though. What PDF URL would you like it to point to?

**Comment by p4bl0-** [comment]
Hi,

Ah, indeed, oaDOI can't find it. On our side, DOAI finds it ;). Proves that collaborating is indeed the way to go!

I guess this URL would be nice: `https://eprint.iacr.org/2015/147.pdf`. The paper is also on HAL, arXiv, and my website, but the IACR ePrint Archive is where people in the cryptology community are used to go.

Thanks!

(I will report the oaDOI "bug" on the linked form :).)

**Comment by hpiwowar** [comment]
Thanks again for reporting this!
Fixed on your Impactstory page.

Is still broken on oaDOI, but hopefully we'll fix it there soon (is bug related to the fact there is an accent in the first author name in the arxiv version but not the Crossref version.  whoops)
